# Dependencies
markdown:         kramdown
kramdown:
   # We're using mathjax because gh-pages forces it
   # we're also usint the auto-render katex extension because of it
   math_engine:   mathjax
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title: JDV's Blog
tagline: CS, Linguistics, Grad School, etc.
email: delvallejacobo@gmail.com
description: A blog on my thoughts about CS, linguistics, grad school, music theory, BWF, and more.
author: JDV
logo: public/favicon.ico
baseurl: "/jblog" # the subpath of your site, e.g. /blog/
url: "https://codewrites.me" # the base hostname & protocol for your site
twitter_username: clinchergt
github_username: clinchergt

plugins: [jekyll-paginate, jekyll-gist, jekyll-sitemap]

paginate:         5
personal:
  repo: https://github.com/clinchergt/jblog
  url: https://jjdv.xyz
  cv: https://jjdv.xyz/personal/cv.pdf

